"use client"

import { useState, useEffect } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { useCNC, type Order, type Client } from "@/lib/contexts/cnc-context"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Plus, ClipboardList, Trash2, X, Loader2, Printer, FileText, IndianRupee, Search, UserPlus, AlertCircle, Share2, Phone, MapPin, Calendar, ChevronDown } from "lucide-react"

const designTypes = [
  "Mandir Jali",
  "Traditional Jali",
  "3D Wall Panel",
  "Engraving",
  "Carving",
  "CNC Cutting",
  "Custom Design",
]

const orderStatuses = ["Pending", "In Progress", "Completed", "Billed"] as const

export function CNCOrders() {
  const { orders, clients, materials, loading, addOrder, updateOrder, deleteOrder, addClient, fetchOrdersByMonth, ordersLoading } = useCNC()
  const searchParams = useSearchParams()
  const initialSearch = searchParams.get("search") || ""
  const [showAddOrder, setShowAddOrder] = useState(false)
  const [activeTab, setActiveTab] = useState("all")
  const [saving, setSaving] = useState(false)
  const [clientErrors, setClientErrors] = useState<Record<string, string>>({})
  const [showJobCard, setShowJobCard] = useState<Order | null>(null)
  const [showPaymentDialog, setShowPaymentDialog] = useState<Order | null>(null)
  const [paymentAmount, setPaymentAmount] = useState(0)
  const [searchQuery, setSearchQuery] = useState(initialSearch)

  // Update search query if URL parameter changes
  useEffect(() => {
    if (initialSearch) {
      setSearchQuery(initialSearch)
      setActiveTab("all") // Ensure we are on the 'all' tab to see the search result

      // Clear the search param from the URL so it doesn't persist on refresh
      const params = new URLSearchParams(window.location.search)
      if (params.has("search")) {
        params.delete("search")
        const newUrl = params.toString() ? `?${params.toString()}` : window.location.pathname
        window.history.replaceState(null, "", newUrl)
      }
    }
  }, [initialSearch])
  const [materialWidth, setMaterialWidth] = useState<number>(0)
  const [materialHeight, setMaterialHeight] = useState<number>(0)
  const [useCustomSize, setUseCustomSize] = useState(false)
  const [paymentMethod, setPaymentMethod] = useState<'Cash' | 'UPI' | 'Card' | 'Bank'>('Cash')
  const [paymentAccount, setPaymentAccount] = useState<'Kamal Jangid' | 'Hiralal Jangid' | ''>('')
  const [showQuickClient, setShowQuickClient] = useState(false)
  const [quickClient, setQuickClient] = useState({ name: "", mobile: "", type: "Individual" as Client["type"] })
  const [addingClient, setAddingClient] = useState(false)
  const [customDesignType, setCustomDesignType] = useState("")
  const [isCustomDesign, setIsCustomDesign] = useState(false)
  const [labourRatePerSqFt, setLabourRatePerSqFt] = useState(0)
  const [dateFilter, setDateFilter] = useState("all") // all, today, week, month, custom
  const [customFromDate, setCustomFromDate] = useState("") // Custom date range start
  const [customToDate, setCustomToDate] = useState("") // Custom date range end
  const [visibleCount, setVisibleCount] = useState(15) // Pagination: show 15 orders at a time

  // Month/Year selector state - defaults to current month
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1) // 1-12
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())

  // Month names for dropdown
  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ]

  // Generate year options (current year and 2 years back)
  const currentYear = new Date().getFullYear()
  const yearOptions = [currentYear, currentYear - 1, currentYear - 2]

  // Fetch orders when month/year changes
  useEffect(() => {
    fetchOrdersByMonth(selectedMonth, selectedYear)
  }, [selectedMonth, selectedYear])

  const generateOrderNumber = () => {
    // Now returns placeholder - actual order number is generated by server
    const date = new Date()
    const prefix = `ORD${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, "0")}`
    return `${prefix}-XXX`
  }

  const getSheetArea = (size: string) => {
    const parts = size.toLowerCase().split("x")
    if (parts.length === 2) {
      const w = parseFloat(parts[0])
      const h = parseFloat(parts[1])
      if (!isNaN(w) && !isNaN(h)) return w * h
    }
    return 32 // Default 8x4
  }

  const [newOrder, setNewOrder] = useState<Partial<Order>>({
    orderNumber: "Auto", // Server will generate
    date: new Date().toISOString().split("T")[0],
    clientId: "",
    designType: "",
    materials: [],
    labourCost: 0,
    totalValue: 0,
    advanceReceived: 0,
    balanceAmount: 0,
    deliveryDate: "",
    status: "Pending",
  })

  const [selectedMaterial, setSelectedMaterial] = useState("")
  const [materialQty, setMaterialQty] = useState(1)

  const addMaterialToOrder = () => {
    if (!selectedMaterial) return
    const material = materials.find((m) => (m.id || m._id) === selectedMaterial)
    if (!material) return

    const updatedMaterials = [...(newOrder.materials || [])]

    let finalQty = materialQty
    let itemCost = materialQty * material.rate

    if (useCustomSize && materialWidth > 0 && materialHeight > 0) {
      const sheetArea = getSheetArea(material.size)
      const customArea = materialWidth * materialHeight
      finalQty = (customArea / sheetArea) * materialQty
      itemCost = finalQty * material.rate
    }

    updatedMaterials.push({
      materialId: selectedMaterial,
      quantity: finalQty,
      width: useCustomSize ? materialWidth : undefined,
      height: useCustomSize ? materialHeight : undefined,
      cost: itemCost,
    })

    const materialCost = updatedMaterials.reduce((sum, m) => sum + m.cost, 0)
    const totalValue = materialCost + (newOrder.labourCost || 0)
    const balanceAmount = totalValue - (newOrder.advanceReceived || 0)

    setNewOrder({
      ...newOrder,
      materials: updatedMaterials,
      totalValue,
      balanceAmount,
    })
    setSelectedMaterial("")
    setMaterialQty(1)
    setMaterialWidth(0)
    setMaterialHeight(0)
    setUseCustomSize(false)
  }

  const removeMaterialFromOrder = (index: number) => {
    const updatedMaterials = [...(newOrder.materials || [])]
    updatedMaterials.splice(index, 1)

    const materialCost = updatedMaterials.reduce((sum, m) => sum + m.cost, 0)
    const totalValue = materialCost + (newOrder.labourCost || 0)
    const balanceAmount = totalValue - (newOrder.advanceReceived || 0)

    setNewOrder({
      ...newOrder,
      materials: updatedMaterials,
      totalValue,
      balanceAmount,
    })
  }

  const updateLabourCost = (ratePerSqFt: number) => {
    setLabourRatePerSqFt(ratePerSqFt)
    const totalArea = getTotalMaterialArea()
    const labourCost = Math.round(ratePerSqFt * totalArea)
    const materialCost = newOrder.materials?.reduce((sum, m) => sum + m.cost, 0) || 0
    const totalValue = materialCost + labourCost
    const balanceAmount = totalValue - (newOrder.advanceReceived || 0)
    setNewOrder({ ...newOrder, labourCost, totalValue, balanceAmount })
  }

  // Calculate total material area in sq ft
  const getTotalMaterialArea = () => {
    if (!newOrder.materials || newOrder.materials.length === 0) return 0
    return newOrder.materials.reduce((total, m) => {
      const material = materials.find((mat) => (mat.id || mat._id) === m.materialId)
      if (!material) return total

      // For custom sizes, use the actual custom area directly
      // For full sheets, use sheet area × quantity
      if (m.width && m.height) {
        // Custom size: 3×5 = 15 sq ft (the custom dimensions are the actual area)
        return total + (m.width * m.height)
      } else {
        // Full sheet: 8×4 = 32 sq ft × quantity
        return total + (getSheetArea(material.size) * m.quantity)
      }
    }, 0)
  }

  const updateAdvance = (advance: number) => {
    const balanceAmount = (newOrder.totalValue || 0) - advance
    setNewOrder({ ...newOrder, advanceReceived: advance, balanceAmount })
  }

  const handleAddOrder = async () => {
    setSaving(true)
    try {
      await addOrder({
        orderNumber: "Pending", // Server generates this
        date: newOrder.date || "",
        clientId: newOrder.clientId || "",
        designType: newOrder.designType || "",
        materials: newOrder.materials || [],
        labourCost: newOrder.labourCost || 0,
        totalValue: newOrder.totalValue || 0,
        advanceReceived: newOrder.advanceReceived || 0,
        payments: (newOrder.advanceReceived || 0) > 0 ? [{
          amount: newOrder.advanceReceived || 0,
          date: new Date().toISOString(),
          method: paymentMethod,
          account: (paymentMethod !== 'Cash') ? (paymentAccount as any) : undefined
        }] : [],
        balanceAmount: newOrder.balanceAmount || 0,
        deliveryDate: newOrder.deliveryDate || "",
        status: newOrder.status as Order["status"],
      })
      setShowAddOrder(false)
      setNewOrder({
        orderNumber: "Auto", // Server will generate
        date: new Date().toISOString().split("T")[0],
        clientId: "",
        designType: "",
        materials: [],
        labourCost: 0,
        totalValue: 0,
        advanceReceived: 0,
        balanceAmount: 0,
        deliveryDate: "",
        status: "Pending",
      })
      setPaymentMethod('Cash')
      setPaymentAccount('')
    } catch (error) {
      console.error("Failed to add order:", error)
    } finally {
      setSaving(false)
    }
  }

  const handleUpdateOrderStatus = async (orderId: string, status: Order["status"]) => {
    try {
      await updateOrder(orderId, { status })
    } catch (error) {
      console.error("Failed to update order:", error)
    }
  }

  const handleDeleteOrder = async (id: string) => {
    try {
      await deleteOrder(id)
    } catch (error) {
      console.error("Failed to delete order:", error)
    }
  }

  const handlePrint = () => {
    window.print()
  }

  const handleShareBill = async () => {
    if (!showJobCard) return
    const client = clients.find(c => (c.id || c._id) === showJobCard.clientId)
    const materialsList = showJobCard.materials.map((m) => {
      const mat = materials.find((mt) => (mt.id || mt._id) === m.materialId)
      return `  • ${mat?.type || 'Material'} ${m.width && m.height ? `(${m.width}×${m.height})` : mat?.size || ''} × ${m.quantity.toFixed(1)} sheets`
    }).join('\n')

    const billText = `
*JANGID HOMES - CNC Workshop*
━━━━━━━━━━━━━━━━━━━━━━━
📋 *Invoice #${showJobCard.orderNumber}*
📅 Date: ${new Date(showJobCard.date).toLocaleDateString("en-IN")}

👤 *Client:* ${client?.name || 'N/A'}
📱 Mobile: ${client?.mobile || 'N/A'}

🔧 *Work:* ${showJobCard.designType}
${showJobCard.deliveryDate ? `📆 Delivery: ${new Date(showJobCard.deliveryDate).toLocaleDateString("en-IN")}` : ''}

📦 *Materials:*
${materialsList}

━━━━━━━━━━━━━━━━━━━━━━━
💰 *Total:* ₹${showJobCard.totalValue.toLocaleString("en-IN")}
✅ *Paid:* ₹${showJobCard.advanceReceived.toLocaleString("en-IN")}
${showJobCard.balanceAmount > 0 ? `⏳ *Balance:* ₹${showJobCard.balanceAmount.toLocaleString("en-IN")}` : '✓ *PAID IN FULL*'}
━━━━━━━━━━━━━━━━━━━━━━━

Thank you for choosing Jangid Homes!
📞 Contact: 9414058690
`.trim()

    if (navigator.share) {
      try {
        await navigator.share({
          title: `Invoice ${showJobCard.orderNumber}`,
          text: billText,
        })
      } catch (err) {
        // User cancelled or share failed, fallback to copy
        await navigator.clipboard.writeText(billText)
        alert('Bill copied to clipboard!')
      }
    } else {
      // Fallback: Copy to clipboard
      await navigator.clipboard.writeText(billText)
      alert('Bill copied to clipboard! You can paste it in WhatsApp or any app.')
    }
  }

  const handleRecordPayment = async () => {
    if (!showPaymentDialog || paymentAmount <= 0) return
    setSaving(true)
    try {
      const orderId = showPaymentDialog.id || showPaymentDialog._id || ""
      const currentAdvance = showPaymentDialog.advanceReceived || 0
      const newAdvance = currentAdvance + paymentAmount
      const newBalance = (showPaymentDialog.totalValue || 0) - newAdvance

      const newPayment = {
        amount: paymentAmount,
        date: new Date().toISOString(),
        method: paymentMethod,
        account: (paymentMethod !== 'Cash') ? (paymentAccount as any) : undefined
      }

      await updateOrder(orderId, {
        advanceReceived: newAdvance,
        payments: [...(showPaymentDialog.payments || []), newPayment],
        balanceAmount: Math.max(0, newBalance),
      })
      setShowPaymentDialog(null)
      setPaymentAmount(0)
      setPaymentMethod('Cash')
      setPaymentAccount('')
    } catch (error) {
      console.error("Failed to record payment:", error)
    } finally {
      setSaving(false)
    }
  }

  // Filter orders by tab, search, and date, then sort by newest first
  const filteredOrders = orders
    .filter((o) => {
      // Tab filter
      const matchesTab = activeTab === "all" || o.status === activeTab

      // Date filter
      let matchesDate = true
      if (dateFilter !== "all") {
        const orderDate = new Date(o.date)
        const today = new Date()
        today.setHours(0, 0, 0, 0)

        if (dateFilter === "today") {
          const orderDay = new Date(orderDate)
          orderDay.setHours(0, 0, 0, 0)
          matchesDate = orderDay.getTime() === today.getTime()
        } else if (dateFilter === "week") {
          const weekAgo = new Date(today)
          weekAgo.setDate(weekAgo.getDate() - 7)
          matchesDate = orderDate >= weekAgo
        } else if (dateFilter === "month") {
          matchesDate = orderDate.getMonth() === today.getMonth() &&
            orderDate.getFullYear() === today.getFullYear()
        } else if (dateFilter === "custom" && customFromDate && customToDate) {
          const fromDate = new Date(customFromDate)
          fromDate.setHours(0, 0, 0, 0)
          const toDate = new Date(customToDate)
          toDate.setHours(23, 59, 59, 999)
          matchesDate = orderDate >= fromDate && orderDate <= toDate
        } else if (dateFilter === "custom") {
          // Custom selected but dates not set - show all
          matchesDate = true
        }
      }

      // Search filter
      if (!searchQuery.trim()) return matchesTab && matchesDate

      const query = searchQuery.toLowerCase()
      // Use clientSnapshot first, fallback to lookup
      const clientName = o.clientSnapshot?.name || clients.find(c => (c.id || c._id) === o.clientId)?.name || ""
      const clientMobile = o.clientSnapshot?.mobile || clients.find(c => (c.id || c._id) === o.clientId)?.mobile || ""
      const matchesSearch =
        o.orderNumber.toLowerCase().includes(query) ||
        clientName.toLowerCase().includes(query) ||
        clientMobile.includes(query) ||
        o.designType.toLowerCase().includes(query) ||
        o.status.toLowerCase().includes(query) // Added: search by status

      return matchesTab && matchesDate && matchesSearch
    })
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()) // Newest first

  const getStatusColor = (status: Order["status"]) => {
    switch (status) {
      case "Pending":
        return "bg-amber-100 text-amber-700 dark:bg-amber-950/50 dark:text-amber-400"
      case "In Progress":
        return "bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400"
      case "Completed":
        return "bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400"
      case "Billed":
        return "bg-slate-100 text-slate-700 dark:bg-slate-800/50 dark:text-slate-400"
      default:
        return "bg-slate-100 text-slate-700 dark:bg-slate-800/50 dark:text-slate-400"
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-48">
        <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full overflow-hidden">
      {/* Sticky Header Section - stays fixed at top */}
      <div className="flex-shrink-0 bg-background pb-3 space-y-3">
        {/* Header - matching dashboard style */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h2 className="text-xl font-semibold text-foreground">Orders</h2>
            <span className="text-sm text-muted-foreground">
              {monthNames[selectedMonth - 1]} {selectedYear} • {orders.length} orders
            </span>
          </div>
          <Dialog open={showAddOrder} onOpenChange={setShowAddOrder}>
            <DialogTrigger asChild>
              <Button size="sm" className="h-8 text-xs">
                <Plus className="w-3.5 h-3.5 mr-1.5" />
                New Order
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl w-[95vw] max-h-[90vh] overflow-y-auto rounded-2xl">
              <DialogHeader>
                <DialogTitle>Create New Order</DialogTitle>
              </DialogHeader>
              <div className="space-y-4 pt-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Order Number</Label>
                    <Input value="Auto-generated" disabled className="bg-muted text-muted-foreground" />
                  </div>
                  <div className="space-y-2">
                    <Label>Order Date</Label>
                    <Input
                      type="date"
                      value={newOrder.date}
                      onChange={(e) => setNewOrder({ ...newOrder, date: e.target.value })}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Client</Label>
                    {/* Client dropdown with add button */}
                    {clients.length > 0 && !showQuickClient ? (
                      <div className="flex gap-2">
                        <Select value={newOrder.clientId} onValueChange={(v) => setNewOrder({ ...newOrder, clientId: v })}>
                          <SelectTrigger className="flex-1">
                            <SelectValue placeholder="Select client" />
                          </SelectTrigger>
                          <SelectContent>
                            {clients.map((c) => {
                              const clientId = c.id || c._id;
                              if (!clientId) return null;
                              return (
                                <SelectItem key={clientId} value={clientId}>
                                  {c.name} <span className="text-muted-foreground text-xs ml-1">({c.type})</span>
                                </SelectItem>
                              );
                            })}
                          </SelectContent>
                        </Select>
                        <Button
                          type="button"
                          variant="outline"
                          size="icon"
                          className="shrink-0"
                          onClick={() => setShowQuickClient(true)}
                          title="Add New Client"
                        >
                          <UserPlus className="w-4 h-4" />
                        </Button>
                      </div>
                    ) : (
                      /* No clients or adding new - show message */
                      <p className="text-sm text-muted-foreground py-2">
                        {clients.length === 0 ? "No clients yet. Add one below." : "Adding new client..."}
                      </p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Label>Design Type</Label>
                    {!isCustomDesign ? (
                      <div className="flex gap-2">
                        <Select
                          value={newOrder.designType}
                          onValueChange={(v) => {
                            if (v === "__custom__") {
                              setIsCustomDesign(true)
                              setNewOrder({ ...newOrder, designType: "" })
                            } else {
                              setNewOrder({ ...newOrder, designType: v })
                            }
                          }}
                        >
                          <SelectTrigger className="flex-1">
                            <SelectValue placeholder="Select design" />
                          </SelectTrigger>
                          <SelectContent>
                            {designTypes.map((d) => (
                              <SelectItem key={d} value={d}>
                                {d}
                              </SelectItem>
                            ))}
                            <SelectItem value="__custom__" className="text-primary font-medium">
                              + Add Custom Design
                            </SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    ) : (
                      <div className="flex gap-2">
                        <Input
                          placeholder="Enter custom design type..."
                          value={customDesignType}
                          onChange={(e) => {
                            setCustomDesignType(e.target.value)
                            setNewOrder({ ...newOrder, designType: e.target.value })
                          }}
                          className="flex-1"
                          autoFocus
                        />
                        <Button
                          type="button"
                          variant="outline"
                          size="icon"
                          onClick={() => {
                            setIsCustomDesign(false)
                            setCustomDesignType("")
                            setNewOrder({ ...newOrder, designType: "" })
                          }}
                          title="Back to list"
                        >
                          <X className="w-4 h-4" />
                        </Button>
                      </div>
                    )}
                  </div>
                </div>

                {/* Quick Add Client Section - Full Width */}
                {(clients.length === 0 || showQuickClient) && (
                  <div className="p-4 bg-gradient-to-r from-primary/5 to-primary/10 border border-primary/20 rounded-xl space-y-3">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <UserPlus className="w-4 h-4 text-primary" />
                        <span className="font-medium text-sm">
                          {clients.length === 0 ? "Add Your First Client" : "Quick Add New Client"}
                        </span>
                      </div>
                      {clients.length > 0 && (
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          className="h-7 text-xs"
                          onClick={() => setShowQuickClient(false)}
                        >
                          <X className="w-3 h-3 mr-1" />
                          Cancel
                        </Button>
                      )}
                    </div>
                    <div className="grid grid-cols-3 gap-3">
                      <div className="space-y-1">
                        <Input
                          placeholder="Client Name *"
                          value={quickClient.name}
                          onChange={(e) => {
                            setQuickClient({ ...quickClient, name: e.target.value })
                            if (clientErrors.name) setClientErrors({ ...clientErrors, name: "" })
                          }}
                          className={clientErrors.name ? "border-destructive focus-visible:ring-destructive" : ""}
                        />
                        {clientErrors.name && (
                          <p className="text-[10px] font-medium text-destructive flex items-center gap-1">
                            <AlertCircle className="w-3 h-3" />
                            {clientErrors.name}
                          </p>
                        )}
                      </div>
                      <div className="space-y-1">
                        <Input
                          placeholder="Mobile Number"
                          value={quickClient.mobile}
                          onChange={(e) => {
                            setQuickClient({ ...quickClient, mobile: e.target.value })
                            if (clientErrors.mobile) setClientErrors({ ...clientErrors, mobile: "" })
                          }}
                          className={clientErrors.mobile ? "border-destructive focus-visible:ring-destructive" : ""}
                        />
                        {clientErrors.mobile && (
                          <p className="text-[10px] font-medium text-destructive flex items-center gap-1">
                            <AlertCircle className="w-3 h-3" />
                            {clientErrors.mobile}
                          </p>
                        )}
                      </div>
                      <Select
                        value={quickClient.type}
                        onValueChange={(v) => setQuickClient({ ...quickClient, type: v as Client["type"] })}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Type" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Individual">Individual</SelectItem>
                          <SelectItem value="Architect">Architect</SelectItem>
                          <SelectItem value="Contractor">Contractor</SelectItem>
                          <SelectItem value="Shop">Shop</SelectItem>
                          <SelectItem value="Other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <Button
                      type="button"
                      className="w-full"
                      disabled={addingClient}
                      onClick={async () => {
                        const newErrors: Record<string, string> = {}
                        if (!quickClient.name.trim()) newErrors.name = "Required"
                        if (!quickClient.mobile.trim()) {
                          newErrors.mobile = "Required"
                        } else if (!/^\d{10}$/.test(quickClient.mobile.trim())) {
                          newErrors.mobile = "10 digits"
                        }

                        if (Object.keys(newErrors).length > 0) {
                          setClientErrors(newErrors)
                          return
                        }

                        setAddingClient(true)
                        try {
                          await addClient({
                            name: quickClient.name,
                            mobile: quickClient.mobile,
                            type: quickClient.type,
                            address: "",
                            gst: "",
                            outstandingBalance: 0
                          })
                          setQuickClient({ name: "", mobile: "", type: "Individual" })
                          setShowQuickClient(false)
                          setClientErrors({})
                        } catch (error) {
                          console.error("Failed to add client:", error)
                        } finally {
                          setAddingClient(false)
                        }
                      }}
                    >
                      {addingClient && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                      <UserPlus className="w-4 h-4 mr-2" />
                      Add Client
                    </Button>
                  </div>
                )}

                <div className="space-y-2">
                  <Label>Materials Used</Label>
                  <div className="flex gap-2">
                    <Select value={selectedMaterial} onValueChange={setSelectedMaterial}>
                      <SelectTrigger className="flex-1">
                        <SelectValue placeholder="Select material" />
                      </SelectTrigger>
                      <SelectContent>
                        {materials.map((m) => {
                          const materialId = m.id || m._id;
                          if (!materialId) return null;
                          return (
                            <SelectItem key={materialId} value={materialId}>
                              {m.type} - {m.size} ({m.thickness}mm) - Stock: {m.currentStock}
                            </SelectItem>
                          );
                        })}
                      </SelectContent>
                    </Select>
                    <Input
                      type="number"
                      className="w-20"
                      value={materialQty}
                      onChange={(e) => setMaterialQty(Number(e.target.value))}
                      min={1}
                    />
                    <Button onClick={addMaterialToOrder} disabled={!selectedMaterial}>
                      Add
                    </Button>
                  </div>
                  {selectedMaterial && (
                    <div className="flex items-center gap-4 p-2 bg-primary/5 rounded-lg border border-primary/10">
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          id="customSize"
                          checked={useCustomSize}
                          onChange={(e) => setUseCustomSize(e.target.checked)}
                          className="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary"
                        />
                        <Label htmlFor="customSize" className="text-xs font-medium cursor-pointer">
                          Custom Size (Width x Height)
                        </Label>
                      </div>
                      {useCustomSize && (
                        <div className="flex items-center gap-2 animate-in fade-in slide-in-from-left-2 duration-200">
                          <Input
                            type="number"
                            placeholder="W"
                            className="w-16 h-8 text-xs"
                            value={materialWidth || ""}
                            onChange={(e) => setMaterialWidth(Number(e.target.value))}
                          />
                          <span className="text-xs text-muted-foreground">x</span>
                          <Input
                            type="number"
                            placeholder="H"
                            className="w-16 h-8 text-xs"
                            value={materialHeight || ""}
                            onChange={(e) => setMaterialHeight(Number(e.target.value))}
                          />
                        </div>
                      )}
                    </div>
                  )}
                  {newOrder.materials && newOrder.materials.length > 0 && (
                    <div className="mt-2 space-y-2">
                      {newOrder.materials.map((m, index) => {
                        const material = materials.find((mat) => (mat.id || mat._id) === m.materialId)
                        return (
                          <div key={`${m.materialId}-${index}`} className="flex justify-between items-center p-2 bg-muted rounded">
                            <span>
                              {material ? (
                                <>
                                  {material.type} - {material.size} ({material.thickness}mm)
                                  {m.width && m.height && (
                                    <span className="ml-1 text-primary font-medium">
                                      [{m.width}x{m.height}]
                                    </span>
                                  )}
                                  <span className="ml-1 text-muted-foreground">x {m.quantity.toFixed(2)} sheets</span>
                                </>
                              ) : "Unknown"}
                            </span>
                            <div className="flex items-center gap-2">
                              <span className="font-medium">₹{m.cost.toLocaleString("en-IN")}</span>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-6 w-6"
                                onClick={() => removeMaterialFromOrder(index)}
                              >
                                <X className="w-4 h-4" />
                              </Button>
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Labour Rate (₹/sq ft)</Label>
                    <div className="flex gap-2 items-center">
                      <Input
                        type="number"
                        value={labourRatePerSqFt || ""}
                        onChange={(e) => updateLabourCost(Number(e.target.value))}
                        placeholder="e.g. 90"
                      />
                      {getTotalMaterialArea() > 0 && (
                        <span className="text-xs text-muted-foreground whitespace-nowrap">
                          × {getTotalMaterialArea().toFixed(1)} sq ft
                        </span>
                      )}
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label>Delivery Date</Label>
                    <Input
                      type="date"
                      value={newOrder.deliveryDate}
                      onChange={(e) => setNewOrder({ ...newOrder, deliveryDate: e.target.value })}
                    />
                  </div>
                </div>

                <div className="p-4 bg-muted rounded-lg space-y-2">
                  <div className="flex justify-between">
                    <span>Material Cost:</span>
                    <span>₹{(newOrder.materials?.reduce((sum, m) => sum + m.cost, 0) || 0).toLocaleString("en-IN")}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="flex items-center gap-1">
                      Labour Cost:
                      {labourRatePerSqFt > 0 && getTotalMaterialArea() > 0 && (
                        <span className="text-xs text-muted-foreground">
                          (₹{labourRatePerSqFt} × {getTotalMaterialArea().toFixed(1)} sq ft)
                        </span>
                      )}
                    </span>
                    <span>₹{(newOrder.labourCost || 0).toLocaleString("en-IN")}</span>
                  </div>
                  <div className="flex justify-between font-bold text-lg border-t pt-2">
                    <span>Total Value:</span>
                    <span>₹{(newOrder.totalValue || 0).toLocaleString("en-IN")}</span>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Advance Received (₹)</Label>
                    <Input
                      type="number"
                      value={newOrder.advanceReceived}
                      onChange={(e) => updateAdvance(Number(e.target.value))}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Balance Amount</Label>
                    <Input
                      value={`₹${(newOrder.balanceAmount || 0).toLocaleString("en-IN")}`}
                      disabled
                      className="bg-muted font-bold"
                    />
                  </div>
                </div>

                {(newOrder.advanceReceived || 0) > 0 && (
                  <div className="grid grid-cols-2 gap-4 p-3 bg-primary/5 rounded-lg border border-primary/10 animate-in fade-in slide-in-from-top-2">
                    <div className="space-y-2">
                      <Label className="text-xs">Payment Method</Label>
                      <Select value={paymentMethod} onValueChange={(v: any) => setPaymentMethod(v)}>
                        <SelectTrigger className="h-8 text-xs">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Cash">Cash</SelectItem>
                          <SelectItem value="UPI">UPI</SelectItem>
                          <SelectItem value="Bank">Bank Transfer</SelectItem>
                          <SelectItem value="Card">Card</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    {paymentMethod !== 'Cash' && (
                      <div className="space-y-2">
                        <Label className="text-xs">Received By</Label>
                        <Select value={paymentAccount} onValueChange={(v: any) => setPaymentAccount(v)}>
                          <SelectTrigger className="h-8 text-xs">
                            <SelectValue placeholder="Select Account" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="Kamal Jangid">Kamal Jangid</SelectItem>
                            <SelectItem value="Hiralal Jangid">Hiralal Jangid</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    )}
                  </div>
                )}

                <Button onClick={handleAddOrder} className="w-full" disabled={!newOrder.clientId || !newOrder.designType || saving}>
                  {saving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                  Create Order
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>

        {/* Search and Filter - Professional compact style */}
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
            <Input
              placeholder="Search orders, clients, or designs..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9 h-9 text-sm"
            />
            {searchQuery && (
              <Button
                variant="ghost"
                size="icon"
                className="absolute right-1 top-1/2 -translate-y-1/2 h-6 w-6"
                onClick={() => setSearchQuery("")}
              >
                <X className="w-3.5 h-3.5" />
              </Button>
            )}
          </div>
        </div>

        {/* Status Tabs with Date Filter */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <TabsList className="h-9 p-1 overflow-x-auto">
              <TabsTrigger value="all" className="text-xs px-3 h-7">All ({orders.length})</TabsTrigger>
              <TabsTrigger value="Pending" className="text-xs px-3 h-7">Pending ({orders.filter((o) => o.status === "Pending").length})</TabsTrigger>
              <TabsTrigger value="In Progress" className="text-xs px-3 h-7">In Progress ({orders.filter((o) => o.status === "In Progress").length})</TabsTrigger>
              <TabsTrigger value="Completed" className="text-xs px-3 h-7">Completed ({orders.filter((o) => o.status === "Completed").length})</TabsTrigger>
              <TabsTrigger value="Billed" className="text-xs px-3 h-7">Billed ({orders.filter((o) => o.status === "Billed").length})</TabsTrigger>
            </TabsList>
          </Tabs>

          {/* Date Filter */}
          <div className="flex items-center gap-2">
            <Select value={dateFilter} onValueChange={(v) => {
              setDateFilter(v)
              // Reset custom dates when switching away from custom
              if (v !== "custom") {
                setCustomFromDate("")
                setCustomToDate("")
              }
            }}>
              <SelectTrigger className="w-[140px] h-9 text-xs">
                <Calendar className="w-3.5 h-3.5 mr-1.5 text-muted-foreground" />
                <SelectValue placeholder="Date" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Time</SelectItem>
                <SelectItem value="today">Today</SelectItem>
                <SelectItem value="week">This Week</SelectItem>
                <SelectItem value="month">This Month</SelectItem>
                <SelectItem value="custom">Custom Range</SelectItem>
              </SelectContent>
            </Select>
            {/* Month Selector */}
            <Select value={selectedMonth.toString()} onValueChange={(v) => {
              setSelectedMonth(parseInt(v))
              setVisibleCount(15) // Reset pagination on month change
            }}>
              <SelectTrigger className="w-[110px] h-9 text-xs">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {monthNames.map((month, idx) => (
                  <SelectItem key={idx} value={(idx + 1).toString()} className="text-xs">
                    {month}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {/* Year Selector */}
            <Select value={selectedYear.toString()} onValueChange={(v) => {
              setSelectedYear(parseInt(v))
              setVisibleCount(15) // Reset pagination on year change
            }}>
              <SelectTrigger className="w-[75px] h-9 text-xs">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {yearOptions.map((year) => (
                  <SelectItem key={year} value={year.toString()} className="text-xs">
                    {year}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {ordersLoading && <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />}
            {/* Custom Date Range Inputs */}
            {dateFilter === "custom" && (
              <div className="flex items-center gap-1.5 animate-in fade-in slide-in-from-left-2 duration-200">
                <Input
                  type="date"
                  value={customFromDate}
                  onChange={(e) => setCustomFromDate(e.target.value)}
                  className="h-9 w-[130px] text-xs"
                  placeholder="From"
                />
                <span className="text-xs text-muted-foreground">to</span>
                <Input
                  type="date"
                  value={customToDate}
                  onChange={(e) => setCustomToDate(e.target.value)}
                  className="h-9 w-[130px] text-xs"
                  placeholder="To"
                />
                {(customFromDate || customToDate) && (
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8"
                    onClick={() => {
                      setCustomFromDate("")
                      setCustomToDate("")
                    }}
                    title="Clear dates"
                  >
                    <X className="w-3.5 h-3.5" />
                  </Button>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Scrollable Orders Section */}
      <div className="flex-1 overflow-y-auto pt-4">

        {filteredOrders.length === 0 ? (
          <Card className="border shadow-sm">
            <CardContent className="py-10 text-center">
              <ClipboardList className="w-10 h-10 mx-auto text-muted-foreground mb-3" />
              <p className="text-sm text-muted-foreground">No orders found</p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-4">
            <div className="grid gap-3">
              {filteredOrders.slice(0, visibleCount).map((order) => {
                const orderId = order.id || order._id || ""
                // Use clientSnapshot if available, fallback to lookup for older orders
                const clientName = order.clientSnapshot?.name || clients.find((c) => (c.id || c._id) === order.clientId)?.name || "Unknown Client"
                return (
                  <Card key={orderId} className="border shadow-sm hover:shadow-md transition-all">
                    <CardContent className="p-4">
                      {/* Main Content Grid */}
                      <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4">
                        {/* Left Section - Order Info */}
                        <div className="flex-1 min-w-0 space-y-2">
                          {/* Header Row */}
                          <div className="flex flex-wrap items-center gap-2">
                            <h3 className="text-base font-semibold text-foreground">{order.orderNumber}</h3>
                            <span className={`px-2 py-0.5 rounded-full text-[10px] font-medium uppercase tracking-wide ${getStatusColor(order.status)}`}>
                              {order.status}
                            </span>
                          </div>

                          {/* Client & Design Info */}
                          <div className="flex items-center gap-2 text-sm">
                            <span className="font-medium text-foreground">{clientName}</span>
                            <span className="text-muted-foreground">•</span>
                            <span className="text-muted-foreground">{order.designType || "Job"}</span>
                          </div>

                          {/* Date & Delivery */}
                          <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                            <span>Ordered: {order.date ? new Date(order.date).toLocaleDateString("en-IN", { day: "numeric", month: "short" }) : "N/A"}</span>
                            {order.deliveryDate && (
                              <>
                                <span>•</span>
                                <span className="text-primary font-medium">Due: {new Date(order.deliveryDate).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</span>
                              </>
                            )}
                          </div>

                          {/* Materials - Compact Display */}
                          {order.materials.length > 0 && (
                            <div className="flex flex-wrap gap-1.5 pt-1">
                              {order.materials.slice(0, 3).map((m, idx) => {
                                // Use materialSnapshot if available, fallback to lookup
                                const matType = m.materialSnapshot?.type || materials.find((mat) => (mat.id || mat._id) === m.materialId)?.type || "Material"
                                return (
                                  <span key={idx} className="text-[10px] px-2 py-0.5 bg-muted rounded-full text-muted-foreground">
                                    {matType} {m.width && m.height ? `${m.width}×${m.height}` : ""} ×{m.quantity.toFixed(1)}
                                  </span>
                                )
                              })}
                              {order.materials.length > 3 && (
                                <span className="text-[10px] px-2 py-0.5 bg-muted rounded-full text-muted-foreground">
                                  +{order.materials.length - 3} more
                                </span>
                              )}
                            </div>
                          )}
                        </div>

                        {/* Right Section - Financial Info */}
                        <div className="flex sm:flex-col items-center sm:items-end justify-between gap-3 sm:text-right min-w-fit">
                          <div>
                            <p className="text-lg font-bold text-foreground">₹{(order.totalValue || 0).toLocaleString("en-IN")}</p>
                            <p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">Total Value</p>
                          </div>
                          <div className="text-right">
                            {(order.balanceAmount || 0) > 0 ? (
                              <>
                                <p className="text-base font-bold text-amber-600">₹{(order.balanceAmount || 0).toLocaleString("en-IN")}</p>
                                <p className="text-[10px] font-medium uppercase tracking-wide text-amber-600/70">Balance Due</p>
                              </>
                            ) : (
                              <>
                                <p className="text-base font-bold text-green-600">Paid</p>
                                <p className="text-[10px] font-medium uppercase tracking-wide text-green-600/70">Complete</p>
                              </>
                            )}
                          </div>
                        </div>
                      </div>

                      {/* Payment History - Compact */}
                      {order.payments && order.payments.length > 0 && (
                        <div className="mt-3 pt-3 border-t border-border/50">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">Payments:</span>
                            {order.payments.slice(-3).map((p, idx) => (
                              <span key={idx} className="inline-flex items-center gap-1 text-[10px] px-2 py-0.5 bg-green-50 dark:bg-green-950/30 text-green-700 dark:text-green-400 rounded-full">
                                ₹{p.amount.toLocaleString("en-IN")}
                                <span className="text-green-600/70 dark:text-green-500/70">
                                  ({p.method}{p.account && p.method !== 'Cash' ? ` → ${p.account}` : ''})
                                </span>
                              </span>
                            ))}
                            {order.payments.length > 3 && (
                              <span className="text-[10px] text-muted-foreground">+{order.payments.length - 3} more</span>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Actions Row */}
                      <div className="flex flex-wrap items-center justify-between gap-2 mt-3 pt-3 border-t border-border/50">
                        <Select
                          value={order.status}
                          onValueChange={(v) => handleUpdateOrderStatus(orderId, v as Order["status"])}
                        >
                          <SelectTrigger className="h-8 w-32 text-xs">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {orderStatuses.map((s) => (
                              <SelectItem key={s} value={s} className="text-xs">
                                {s}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>

                        <div className="flex items-center gap-1.5">
                          <Button
                            variant="outline"
                            size="sm"
                            className="h-8 px-3 text-xs gap-1.5"
                            onClick={() => setShowJobCard(order)}
                          >
                            <FileText className="w-3.5 h-3.5" />
                            <span className="hidden sm:inline">Job Card</span>
                          </Button>
                          {order.balanceAmount > 0 && (
                            <Button
                              size="sm"
                              className="h-8 px-3 text-xs gap-1.5 bg-green-600 hover:bg-green-700"
                              onClick={() => {
                                setShowPaymentDialog(order)
                                setPaymentAmount(order.balanceAmount)
                              }}
                            >
                              <IndianRupee className="w-3.5 h-3.5" />
                              <span className="hidden sm:inline">Payment</span>
                            </Button>
                          )}
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-muted-foreground hover:text-destructive"
                            onClick={() => handleDeleteOrder(orderId)}
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )
              })}
            </div>
            {/* Show More Button */}
            {visibleCount < filteredOrders.length && (
              <div className="flex justify-center mt-6">
                <Button
                  variant="outline"
                  onClick={() => setVisibleCount((prev) => prev + 15)}
                  className="w-full max-w-xs h-10 border-dashed hover:border-primary hover:text-primary transition-all"
                >
                  Show More ({filteredOrders.length - visibleCount} remaining)
                </Button>
              </div>
            )}
          </div>
        )}
        {/* Professional Invoice / Bill Dialog */}
        <Dialog open={!!showJobCard} onOpenChange={(o) => !o && setShowJobCard(null)}>
          <DialogContent className="max-w-2xl w-[95vw] max-h-[90vh] overflow-y-auto rounded-2xl printing-area">
            <DialogHeader className="print:hidden">
              <DialogTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Invoice / Bill
              </DialogTitle>
            </DialogHeader>

            {showJobCard && (() => {
              const client = clients.find(c => (c.id || c._id) === showJobCard.clientId)
              // Use snapshot if available, fallback to lookup
              const clientName = showJobCard.clientSnapshot?.name || client?.name || "N/A"
              const clientMobile = showJobCard.clientSnapshot?.mobile || client?.mobile
              const clientAddress = showJobCard.clientSnapshot?.address || client?.address
              return (
                <div className="space-y-5 pt-2">
                  {/* Company Header */}
                  <div className="text-center border-b-2 border-primary pb-4">
                    <h1 className="text-2xl font-bold text-foreground tracking-tight">JANGID HOMES</h1>
                    <p className="text-xs text-muted-foreground font-medium uppercase tracking-widest mt-1">CNC Workshop & Interiors</p>
                    <div className="flex items-center justify-center gap-4 text-xs text-muted-foreground mt-2">
                      <span className="flex items-center gap-1">
                        <Phone className="w-3 h-3" />
                        9929981304
                      </span>
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3 h-3" />
                        Jaipur, Rajasthan
                      </span>
                    </div>
                  </div>

                  {/* Invoice Info Row */}
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Invoice No.</p>
                      <p className="text-xl font-bold text-foreground">{showJobCard.orderNumber}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Date</p>
                      <p className="text-sm font-semibold text-foreground">{new Date(showJobCard.date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p>
                      {showJobCard.deliveryDate && (
                        <p className="text-xs text-primary font-medium mt-0.5">
                          Due: {new Date(showJobCard.deliveryDate).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}
                        </p>
                      )}
                    </div>
                  </div>

                  {/* Client & Work Details */}
                  <div className="grid grid-cols-2 gap-4 p-4 bg-muted/50 rounded-xl">
                    <div>
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">Bill To</p>
                      <p className="text-base font-bold text-foreground">{clientName}</p>
                      {clientMobile && (
                        <p className="text-sm text-muted-foreground flex items-center gap-1">
                          <Phone className="w-3 h-3" />
                          {clientMobile}
                        </p>
                      )}
                      {clientAddress && (
                        <p className="text-xs text-muted-foreground mt-1">{clientAddress}</p>
                      )}
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">Work Description</p>
                      <p className="text-lg font-bold text-primary">{showJobCard.designType}</p>
                    </div>
                  </div>

                  {/* Items Table with Pricing */}
                  <div className="border border-border rounded-xl overflow-hidden">
                    <table className="w-full text-sm">
                      <thead className="bg-primary/10">
                        <tr className="text-[10px] uppercase font-semibold tracking-wide text-primary">
                          <th className="text-left p-3">Item Description</th>
                          <th className="text-center p-3">Size</th>
                          <th className="text-center p-3">Qty</th>
                          <th className="text-right p-3">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border">
                        {showJobCard?.materials?.map((m, idx) => {
                          const mat = materials.find((mt) => (mt.id || mt._id) === m.materialId)
                          return (
                            <tr key={idx} className="bg-background">
                              <td className="p-3">
                                <span className="font-semibold text-foreground">{mat?.type || 'Material'}</span>
                                <span className="text-muted-foreground ml-1 text-xs">({mat?.thickness}mm)</span>
                              </td>
                              <td className="p-3 text-center text-muted-foreground">
                                {m.width && m.height ? (
                                  <span className="font-medium text-foreground">{m.width}×{m.height} ft</span>
                                ) : (
                                  <span>{mat?.size}</span>
                                )}
                              </td>
                              <td className="p-3 text-center font-medium">{m.quantity.toFixed(2)}</td>
                              <td className="p-3 text-right font-semibold">₹{m.cost.toLocaleString("en-IN")}</td>
                            </tr>
                          )
                        })}
                        {/* Labour Cost Row */}
                        {(showJobCard.labourCost || 0) > 0 && (
                          <tr className="bg-background">
                            <td className="p-3" colSpan={3}>
                              <span className="font-semibold text-foreground">Labour & Finishing Charges</span>
                            </td>
                            <td className="p-3 text-right font-semibold">₹{(showJobCard.labourCost || 0).toLocaleString("en-IN")}</td>
                          </tr>
                        )}
                      </tbody>
                      <tfoot className="bg-muted/50">
                        <tr className="border-t-2 border-primary/20">
                          <td colSpan={3} className="p-3 text-right font-bold text-foreground">Total Amount</td>
                          <td className="p-3 text-right">
                            <span className="text-lg font-bold text-foreground">₹{(showJobCard.totalValue || 0).toLocaleString("en-IN")}</span>
                          </td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>

                  {/* Payment History */}
                  {showJobCard?.payments && showJobCard.payments.length > 0 && (
                    <div className="space-y-2">
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Payment History</p>
                      <div className="border border-border rounded-xl overflow-hidden">
                        <table className="w-full text-sm">
                          <thead className="bg-green-50 dark:bg-green-950/30">
                            <tr className="text-[10px] uppercase font-semibold tracking-wide text-green-700 dark:text-green-400">
                              <th className="text-left p-2.5">Date</th>
                              <th className="text-left p-2.5">Method</th>
                              <th className="text-left p-2.5">Received By</th>
                              <th className="text-right p-2.5">Amount</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-border">
                            {showJobCard?.payments?.map((p, idx) => (
                              <tr key={idx}>
                                <td className="p-2.5 text-muted-foreground">{new Date(p.date).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</td>
                                <td className="p-2.5">
                                  <span className="px-2 py-0.5 bg-muted rounded-full text-xs font-medium">{p.method}</span>
                                </td>
                                <td className="p-2.5">
                                  {p.method !== 'Cash' && p.account ? (
                                    <span className="font-medium text-primary">{p.account}</span>
                                  ) : (
                                    <span className="text-muted-foreground">—</span>
                                  )}
                                </td>
                                <td className="p-2.5 text-right font-semibold text-green-600">₹{p.amount.toLocaleString("en-IN")}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}

                  {/* Financial Summary */}
                  <div className="p-4 rounded-xl border-2 border-dashed border-border space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Total Bill Amount</span>
                      <span className="font-semibold">₹{(showJobCard.totalValue || 0).toLocaleString("en-IN")}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-green-600">Amount Received</span>
                      <span className="font-semibold text-green-600">₹{(showJobCard.advanceReceived || 0).toLocaleString("en-IN")}</span>
                    </div>
                    <div className="flex justify-between text-base pt-2 border-t border-border">
                      {(showJobCard.balanceAmount || 0) > 0 ? (
                        <>
                          <span className="font-bold text-amber-600">Balance Due</span>
                          <span className="font-bold text-amber-600">₹{(showJobCard.balanceAmount || 0).toLocaleString("en-IN")}</span>
                        </>
                      ) : (
                        <>
                          <span className="font-bold text-green-600">Status</span>
                          <span className="font-bold text-green-600 flex items-center gap-1">✓ PAID IN FULL</span>
                        </>
                      )}
                    </div>
                  </div>

                  {/* Footer Note */}
                  <div className="text-center pt-2 border-t border-dashed border-border">
                    <p className="text-xs text-muted-foreground">Thank you for choosing Jangid Homes!</p>
                    <p className="text-[10px] text-muted-foreground mt-1">This is a computer-generated invoice.</p>
                  </div>

                  {/* Action Buttons */}
                  <div className="flex flex-wrap justify-end gap-2 print:hidden pt-2">
                    <Button variant="outline" size="sm" onClick={() => setShowJobCard(null)} className="h-9">
                      Close
                    </Button>
                    <Button variant="outline" size="sm" onClick={handleShareBill} className="h-9 gap-1.5">
                      <Share2 className="w-4 h-4" />
                      Share
                    </Button>
                    <Button size="sm" onClick={handlePrint} className="h-9 gap-1.5">
                      <Printer className="w-4 h-4" />
                      Print
                    </Button>
                  </div>
                </div>
              )
            })()}
          </DialogContent>
        </Dialog>

        {/* Record Payment Dialog */}
        <Dialog open={!!showPaymentDialog} onOpenChange={(o) => !o && setShowPaymentDialog(null)}>
          <DialogContent className="max-w-md w-[95vw] rounded-2xl">
            <DialogHeader>
              <DialogTitle>Record Payment</DialogTitle>
            </DialogHeader>

            {showPaymentDialog && (
              <div className="space-y-4 pt-4">
                <div className="p-4 bg-muted rounded-lg space-y-2">
                  <div className="flex justify-between text-sm">
                    <span>Order Number:</span>
                    <span className="font-bold">{showPaymentDialog?.orderNumber}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span>Client:</span>
                    <span className="font-medium">{showPaymentDialog?.clientSnapshot?.name || clients.find(c => (c.id || c._id) === showPaymentDialog.clientId)?.name || "Unknown"}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span>Total Value:</span>
                    <span>₹{(showPaymentDialog?.totalValue || 0).toLocaleString("en-IN")}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span>Already Paid:</span>
                    <span className="text-green-600">₹{(showPaymentDialog?.advanceReceived || 0).toLocaleString("en-IN")}</span>
                  </div>
                  <div className="flex justify-between text-sm font-bold border-t pt-2">
                    <span>Pending Balance:</span>
                    <span className="text-amber-600">₹{(showPaymentDialog?.balanceAmount || 0).toLocaleString("en-IN")}</span>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label>Payment Amount (₹)</Label>
                  <Input
                    type="number"
                    value={paymentAmount}
                    onChange={(e) => setPaymentAmount(Math.min(Number(e.target.value), showPaymentDialog?.balanceAmount || 0))}
                    max={showPaymentDialog?.balanceAmount}
                    min={0}
                    className="text-lg font-bold"
                  />
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setPaymentAmount(Math.round((showPaymentDialog?.balanceAmount || 0) * 0.5))}
                    >
                      50%
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setPaymentAmount(showPaymentDialog?.balanceAmount || 0)}
                    >
                      Full Amount
                    </Button>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Payment Method</Label>
                    <Select value={paymentMethod} onValueChange={(v: any) => setPaymentMethod(v)}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="Cash">Cash</SelectItem>
                        <SelectItem value="UPI">UPI</SelectItem>
                        <SelectItem value="Bank">Bank Transfer</SelectItem>
                        <SelectItem value="Card">Card</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  {paymentMethod !== 'Cash' && (
                    <div className="space-y-2">
                      <Label>Received By</Label>
                      <Select value={paymentAccount} onValueChange={(v: any) => setPaymentAccount(v)}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select Account" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Kamal Jangid">Kamal Jangid</SelectItem>
                          <SelectItem value="Hiralal Jangid">Hiralal Jangid</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  )}
                </div>

                <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
                  <div className="flex justify-between text-sm">
                    <span>New Balance After Payment:</span>
                    <span className="font-bold text-green-700">
                      ₹{Math.max(0, (showPaymentDialog.balanceAmount || 0) - paymentAmount).toLocaleString("en-IN")}
                    </span>
                  </div>
                </div>

                <div className="flex gap-3 pt-2">
                  <Button variant="outline" className="flex-1" onClick={() => setShowPaymentDialog(null)}>
                    Cancel
                  </Button>
                  <Button
                    className="flex-1 bg-green-600 hover:bg-green-700"
                    onClick={handleRecordPayment}
                    disabled={paymentAmount <= 0 || saving}
                  >
                    {saving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                    Confirm Payment
                  </Button>
                </div>
              </div>
            )}
          </DialogContent>
        </Dialog>

        <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          .printing-area, .printing-area * {
            visibility: visible;
          }
          .printing-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            padding: 0;
            margin: 0;
            box-shadow: none;
            border: none;
          }
        }
      `}</style>
      </div>
    </div >
  )
}
